ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "24.8.0"
    hooks:
      - id: black
